// repos.ts
export interface GithubRepo {
	owner: string;
	repo: string; // Geändert von 'name' zu 'repo'
}

export const repos: GithubRepo[] = [
	{ owner: 'amerkurev', repo: 'doku' },
	{ owner: 'bluewave-labs', repo: 'checkmate' },
	{ owner: 'chatwoot', repo: 'chatwoot' },
	{ owner: 'coollabsio', repo: 'coolify' },
	{ owner: 'CorentinTh', repo: 'it-tools' },
	{ owner: 'dani-garcia', repo: 'vaultwarden' },
	{ owner: 'directus', repo: 'directus' },
	{ owner: 'docker-mailserver', repo: 'docker-mailserver' },
	{ owner: 'docsifyjs', repo: 'docsify' },
	{ owner: 'dockur', repo: 'windows' },
	{ owner: 'dockur', repo: 'windows-arm' },
	{ owner: 'duplicati', repo: 'duplicati' },
	{ owner: 'elastic', repo: 'elasticsearch' },
	{ owner: 'formbricks', repo: 'formbricks' },
	{ owner: 'gethomepage', repo: 'homepage' },
	{ owner: 'hcengineering', repo: 'platform' },
	{ owner: 'huntabyte', repo: 'shadcn-svelte' },
	{ owner: 'kimai', repo: 'kimai' },
	{ owner: 'Lissy93', repo: 'dashy' },
	{ owner: 'louislam', repo: 'uptime-kuma' },
	{ owner: 'makeplane', repo: 'plane' },
	{ owner: 'medusajs', repo: 'medusa' },
	{ owner: 'meilisearch', repo: 'meilisearch' },
	{ owner: 'n8n-io', repo: 'n8n' },
	{ owner: 'netdata', repo: 'netdata' },
	{ owner: 'nicolargo', repo: 'glances' },
	{ owner: 'outline', repo: 'outline' },
	{ owner: 'paul-gauthier', repo: 'aider' },
	{ owner: 'payloadcms', repo: 'payload' },
	{ owner: 'pimox', repo: 'pimox7' },
	{ owner: 'pocketbase', repo: 'pocketbase' },
	{ owner: 'postalserver', repo: 'postal' },
	{ owner: 'QuivrHQ', repo: 'quivr' },
	{ owner: 'renovatebot', repo: 'renovate' },
	{ owner: 'requarks', repo: 'wiki' },
	{ owner: 'sanity-io', repo: 'sanity' },
	{ owner: 'solidtime-io', repo: 'solidtime' },
	{ owner: 'storybookjs', repo: 'storybook' },
	{ owner: 'strapi', repo: 'strapi' },
	{ owner: 'sveltejs', repo: 'kit' },
	{ owner: 'sveltejs', repo: 'svelte' },
	{ owner: 'tailwindlabs', repo: 'tailwindcss' },
	{ owner: 'thedaviddias', repo: 'Front-End-Checklist' },
	{ owner: 'toolbeam', repo: 'openauth' },
	{ owner: 'twentyhq', repo: 'twenty' },
	{ owner: 'umami-software', repo: 'umami' },
	{ owner: 'unsend-dev', repo: 'unsend' },
	{ owner: 'TYPO3', repo: 'typo3' },
	{ owner: 'zammad', repo: 'zammad' }
] as const;
